version: '3.8'

services:
  postgress:
    container_name: postgress
    image: postgres:14.0-alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    volumes:
      - ./database:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    volumes:
      - ./pgadmin:/var/lib/pgadmin/
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - postgress
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}

  server:
    container_name: server
    build:
      context: ./server
    depends_on:
      - postgress
      - pgadmin
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
      TYPEORM_CONNECTION: ${TYPEORM_CONNECTION}
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_DATABASE: ${TYPEORM_DATABASE}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_HOST: postgress
#  client:
#    container_name: client
#    build:
#      context: ./client
#    depends_on:
#      - server
#    restart: unless-stopped
#    ports:
#      - '80:80'
