/**
 * Изображение
 */
export enum FILE_FORMAT_IMAGE {
  BMP = 'image/bmp',// .bmp - Bitmap Image File
  CGM = 'image/cgm',// .cgm - Computer Graphics Metafile
  G3 = 'image/g3fax',// .g3 - G3 Fax Image
  GIF = 'image/gif',// .gif - Graphics Interchange Format
  IEF = 'image/ief',// .ief - Image Exchange Format
  JPG = 'image/jpeg',// .jpeg, .jpg - JPEG Image
  KTX = 'image/ktx',// .ktx - OpenGL Textures (KTX)
  PJPEG = 'image/pjpeg',// .pjpeg - JPEG Image (Progressive)
  PNG = 'image/png',// .png - Portable Network Graphics (PNG)
  BTIF = 'image/prs.btif',// .btif - BTIF
  SVG = 'image/svg+xml',// .svg - Scalable Vector Graphics (SVG)
  TIFF = 'image/tiff',// .tiff - Tagged Image File Format
  PSD = 'image/vnd.adobe.photoshop',// .psd - Photoshop Document
  UVI = 'image/vnd.dece.graphic',// .uvi - DECE Graphic
  DJVU = 'image/vnd.djvu',// .djvu - DjVu
  SUB = 'image/vnd.dvb.subtitle',// .sub - Close Captioning - Subtitle
  DWG = 'image/vnd.dwg',// .dwg - DWG Drawing
  DXF = 'image/vnd.dxf',// .dxf - AutoCAD DXF
  FBS = 'image/vnd.fastbidsheet',// .fbs - FastBid Sheet
  FPX = 'image/vnd.fpx',// .fpx - FlashPix
  FST = 'image/vnd.fst',// .fst - FAST Search & Transfer ASA
  MMR = 'image/vnd.fujixerox.edmics-mmr',// .mmr - EDMICS 2000
  RLC = 'image/vnd.fujixerox.edmics-rlc',// .rlc - EDMICS 2000
  MDI = 'image/vnd.ms-modi',// .mdi - Microsoft Document Imaging Format
  NPX = 'image/vnd.net-fpx',// .npx - FlashPix
  WBMP = 'image/vnd.wap.wbmp',// .wbmp - WAP Bitamp (WBMP)
  XIF = 'image/vnd.xiff',// .xif - eXtended Image File Format (XIFF)
  WEBP = 'image/webp',// .webp - WebP Image
  RAS = 'image/x-cmu-raster',// .ras - CMU Image
  CMX = 'image/x-cmx',// .cmx - Corel Metafile Exchange (CMX)
  FH = 'image/x-freehand',// .fh - FreeHand MX
  ICO = 'image/x-icon',// .ico - Icon Image
  PCX = 'image/x-pcx',// .pcx - PCX Image
  PIC = 'image/x-pict',// .pic - PICT Image
  PNM = 'image/x-portable-anymap',// .pnm - Portable Anymap Image
  PBM = 'image/x-portable-bitmap',// .pbm - Portable Bitmap Format
  PGM = 'image/x-portable-graymap',// .pgm - Portable Graymap Format
  PPM = 'image/x-portable-pixmap',// .ppm - Portable Pixmap Format
  RGB = 'image/x-rgb',// .rgb - Silicon Graphics RGB Bitmap
  XBM = 'image/x-xbitmap',// .xbm - X BitMap
  XPM = 'image/x-xpixmap',// .xpm - X PixMap
  XWD = 'image/x-xwindowdump',// .xwd - X Window Dump
}

/**
 * Аудио
 */
export enum FILE_FORMAT_AUDIO {
  ADP = 'audio/adpcm',// .adp - Adaptive differential pulse-code modulation
  AU = 'audio/basic',// .au - Sun Audio - Au file format
  MID = 'audio/midi',// .mid - MIDI - Musical Instrument Digital Interface
  MP4A = 'audio/mp4',// .mp4a - MPEG-4 Audio
  MPGA = 'audio/mpeg',// .mpga - MPEG Audio
  OGA = 'audio/ogg',// .oga - Ogg Audio
  UVA = 'audio/vnd.dece.audio',// .uva - DECE Audio
  EOL = 'audio/vnd.digital-winds',// .eol - Digital Winds Music
  DRA = 'audio/vnd.dra',// .dra - DRA Audio
  DTS = 'audio/vnd.dts',// .dts - DTS Audio
  DTSHD = 'audio/vnd.dts.hd',// .dtshd - DTS High Definition Audio
  LVP = 'audio/vnd.lucent.voice',// .lvp - Lucent Voice
  PYA = 'audio/vnd.ms-playready.media.pya',// .pya - Microsoft PlayReady Ecosystem
  ECELP4800 = 'audio/vnd.nuera.ecelp4800',// .ecelp4800 - Nuera ECELP 4800
  ECELP7470 = 'audio/vnd.nuera.ecelp7470',// .ecelp7470 - Nuera ECELP 7470
  ECELP9600 = 'audio/vnd.nuera.ecelp9600',// .ecelp9600 - Nuera ECELP 9600
  RIP = 'audio/vnd.rip',// .rip - Hit'n'Mix
  WEBA = 'audio/webm',// .weba - Open Web Media Project - Audio
  AAC = 'audio/x-aac',// .aac - Advanced Audio Coding (AAC)
  AIF = 'audio/x-aiff',// .aif - Audio Interchange File Format
  M3U = 'audio/x-mpegurl',// .m3u - M3U (Multimedia Playlist)
  WAX = 'audio/x-ms-wax',// .wax - Microsoft Windows Media Audio Redirector
  WMA = 'audio/x-ms-wma',// .wma - Microsoft Windows Media Audio
  RAM = 'audio/x-pn-realaudio',// .ram - Real Audio Sound
  RMP = 'audio/x-pn-realaudio-plugin',// .rmp - Real Audio Sound
  WAV = 'audio/x-wav',// .wav - Waveform Audio File Format (WAV)
}

/**
 * Видео
 */
export enum FILE_FORMAT_VIDEO {
  GPP = 'video/3gpp',// .3gp - 3GP
  GPP2 = 'video/3gpp2',// .3g2 - 3GP2
  H261 = 'video/h261',// .h261 - H.261
  H263 = 'video/h263',// .h263 - H.263
  H264 = 'video/h264',// .h264 - H.264
  JPGV = 'video/jpeg',// .jpgv - JPGVideo
  JPM = 'video/jpm',// .jpm - JPEG 2000 Compound Image File Format
  MJ2 = 'video/mj2',// .mj2 - Motion JPEG 2000
  MP4 = 'video/mp4',// .mp4 - MPEG-4 Video
  MPEG = 'video/mpeg',// .mpeg - MPEG Video
  OGV = 'video/ogg',// .ogv - Ogg Video
  QT = 'video/quicktime',// .qt - Quicktime Video
  UVH = 'video/vnd.dece.hd',// .uvh - DECE High Definition Video
  UVM = 'video/vnd.dece.mobile',// .uvm - DECE Mobile Video
  UVP = 'video/vnd.dece.pd',// .uvp - DECE PD Video
  UVS = 'video/vnd.dece.sd',// .uvs - DECE SD Video
  UVV = 'video/vnd.dece.video',// .uvv - DECE Video
  FVT = 'video/vnd.fvt',// .fvt - FAST Search & Transfer ASA
  MXU = 'video/vnd.mpegurl',// .mxu - MPEG Url
  PYV = 'video/vnd.ms-playready.media.pyv',// .pyv - Microsoft PlayReady Ecosystem Video
  UVU = 'video/vnd.uvvu.mp4',// .uvu - DECE MP4
  VIV = 'video/vnd.vivo',// .viv - Vivo
  WEBM = 'video/webm',// .webm - Open Web Media Project - Video
  F4V = 'video/x-f4v',// .f4v - Flash Video
  FLI = 'video/x-fli',// .fli - FLI/FLC Animation Format
  FLV = 'video/x-flv',// .flv - Flash Video
  M4V = 'video/x-m4v',// .m4v - M4v
  ASF = 'video/x-ms-asf',// .asf - Microsoft Advanced Systems Format (ASF)
  WM = 'video/x-ms-wm',// .wm - Microsoft Windows Media
  WMV = 'video/x-ms-wmv',// .wmv - Microsoft Windows Media Video
  WMX = 'video/x-ms-wmx',// .wmx - Microsoft Windows Media Audio/Video Playlist
  WVX = 'video/x-ms-wvx',// .wvx - Microsoft Windows Media Video Playlist
  AVI = 'video/x-msvideo',// .avi - Audio Video Interleave (AVI)
  MOVIE = 'video/x-sgi-movie',// .movie - SGI Movie
}

/**
 * Текст
 */
export enum FILE_FORMAT_TEXT {
  ICS = 'text/calendar',// .ics - iCalendar
  CSS = 'text/css',// .css - Cascading Style Sheets (CSS)
  CSV = 'text/csv',// .csv - Comma-Seperated Values
  HTML = 'text/html',// .html - HyperText Markup Language (HTML)
  N3 = 'text/n3',// .n3 - Notation3
  TXT = 'text/plain',// .txt - Text File
  PAR = 'text/plain-bas',// .par - BAS Partitur Format
  DSC = 'text/prs.lines.tag',// .dsc - PRS Lines Tag
  RTX = 'text/richtext',// .rtx - Rich Text Format (RTF)
  SGML = 'text/sgml',// .sgml - Standard Generalized Markup Language (SGML)
  TSV = 'text/tab-separated-values',// .tsv - Tab Seperated Values
  T = 'text/troff',// .t - troff
  TTL = 'text/turtle',// .ttl - Turtle (Terse RDF Triple Language)
  URI = 'text/uri-list',// .uri - URI Resolution Services
  CURL = 'text/vnd.curl',// .curl - Curl - Applet
  DCURL = 'text/vnd.curl.dcurl',// .dcurl - Curl - Detached Applet
  MCURL = 'text/vnd.curl.mcurl',// .mcurl - Curl - Manifest File
  SCURL = 'text/vnd.curl.scurl',// .scurl - Curl - Source Code
  FLY = 'text/vnd.fly',// .fly - mod_fly / fly.cgi
  FLX = 'text/vnd.fmi.flexstor',// .flx - FLEXSTOR
  GV = 'text/vnd.graphviz',// .gv - Graphviz
  DML = 'text/vnd.in3d.3dml',// .3dml - In3D - 3DML
  SPOT = 'text/vnd.in3d.spot',// .spot - In3D - 3DML
  JAD = 'text/vnd.sun.j2me.app-descriptor',// .jad - J2ME App Descriptor
  WML = 'text/vnd.wap.wml',// .wml - Wireless Markup Language (WML)
  WMLS = 'text/vnd.wap.wmlscript',// .wmls - Wireless Markup Language Script (WMLScript)
  S = 'text/x-asm',// .s - Assembler Source File
  C = 'text/x-c',// .c - C Source File
  F = 'text/x-fortran',// .f - Fortran Source File
  JAVA = 'text/x-java-source,java',// .java - Java Source File
  P = 'text/x-pascal',// .p - Pascal Source File
  ETX = 'text/x-setext',// .etx - Setext
  UU = 'text/x-uuencode',// .uu - UUEncode
  VCS = 'text/x-vcalendar',// .vcs - vCalendar
  VCF = 'text/x-vcard',// .vcf - vCard
  YAML = 'text/yaml',// .yaml - YAML Ain't Markup Language / Yet Another Markup Language
}

/**
 * Приложение
 */
export enum FILE_FORMAT_APP {
  AW = 'application/applixware',// .aw - Applixware
  ATOM_XML = 'application/atom+xml',// .atom, .xml - Atom Syndication Format
  ATOMCAT = 'application/atomcat+xml',// .atomcat - Atom Publishing Protocol
  ATOMSVC = 'application/atomsvc+xml',// .atomsvc - Atom Publishing Protocol Service Document
  CCXML = 'application/ccxml+xml,',// .ccxml - Voice Browser Call Control
  CDMIA = 'application/cdmi-capability',// .cdmia - Cloud Data Management Interface (CDMI) - Capability
  CDMIC = 'application/cdmi-container',// .cdmic - Cloud Data Management Interface (CDMI) - Contaimer
  CDMID = 'application/cdmi-domain',// .cdmid - Cloud Data Management Interface (CDMI) - Domain
  CDMIO = 'application/cdmi-object',// .cdmio - Cloud Data Management Interface (CDMI) - Object
  CDMIQ = 'application/cdmi-queue',// .cdmiq - Cloud Data Management Interface (CDMI) - Queue
  CU = 'application/cu-seeme',// .cu - CU-SeeMe
  DAVMOUNT = 'application/davmount+xml',// .davmount - Web Distributed Authoring and Versioning
  DSSC = 'application/dssc+der',// .dssc - Data Structure for the Security Suitability of Cryptographic Algorithms
  XDSSC = 'application/dssc+xml',// .xdssc - Data Structure for the Security Suitability of Cryptographic Algorithms
  ES = 'application/ecmascript',// .es - ECMAScript
  EMMA = 'application/emma+xml',// .emma - Extensible MultiModal Annotation
  EPUB = 'application/epub+zip',// .epub - Electronic Publication
  EXI = 'application/exi',// .exi - Efficient XML Interchange
  PFR = 'application/font-tdpfr',// .pfr - Portable Font Resource
  STK = 'application/hyperstudio',// .stk - Hyperstudio
  IPFIX = 'application/ipfix',// .ipfix - Internet Protocol Flow Information Export
  JAR = 'application/java-archive',// .jar - Java Archive
  SER = 'application/java-serialized-object',// .ser - Java Serialized Object
  CLASS = 'application/java-vm',// .class - Java Bytecode File
  JS = 'application/javascript',// .js - JavaScript
  JSON = 'application/json',// .json - JavaScript Object Notation (JSON)
  HQX = 'application/mac-binhex40',// .hqx - Macintosh BinHex 4.0
  CPT = 'application/mac-compactpro',// .cpt - Compact Pro
  MADS = 'application/mads+xml',// .mads - Metadata Authority Description Schema
  MRC = 'application/marc',// .mrc - MARC Formats
  MRCX = 'application/marcxml+xml',// .mrcx - MARC21 XML Schema
  MA = 'application/mathematica',// .ma - Mathematica Notebooks
  MATHML = 'application/mathml+xml',// .mathml - Mathematical Markup Language
  MBOX = 'application/mbox',// .mbox - Mbox database files
  MSCML = 'application/mediaservercontrol+xml',// .mscml - Media Server Control Markup Language
  META4 = 'application/metalink4+xml',// .meta4 - Metalink
  METS = 'application/mets+xml',// .mets - Metadata Encoding and Transmission Standard
  MODS = 'application/mods+xml',// .mods - Metadata Object Description Schema
  M21 = 'application/mp21',// .m21 - MPEG-21
  MP3 = 'application/mp3',// .mp3 - MPEG4 // ХЗ
  MP4 = 'application/mp4',// .mp4 - MPEG4
  DOC = 'application/msword',// .doc - Microsoft Word
  MXF = 'application/mxf',// .mxf - Material Exchange Format
  BIN = 'application/octet-stream',// .bin - Binary Data
  ODA = 'application/oda',// .oda - Office Document Architecture
  OPF = 'application/oebps-package+xml',// .opf - Open eBook Publication Structure
  OGX = 'application/ogg',// .ogx - Ogg
  ONETOC = 'application/onenote',// .onetoc - Microsoft OneNote
  XER = 'application/patch-ops-error+xml',// .xer - XML Patch Framework
  PDF = 'application/pdf',// .pdf - Adobe Portable Document Format
  PGP = 'application/pgp-encrypted',// .pgp - Pretty Good Privacy
  PRF = 'application/pics-rules',// .prf - PICSRules
  P10 = 'application/pkcs10',// .p10 - PKCS #10 - Certification Request Standard
  P7M = 'application/pkcs7-mime',// .p7m - PKCS #7 - Cryptographic Message Syntax Standard
  P7S = 'application/pkcs7-signature',// .p7s - PKCS #7 - Cryptographic Message Syntax Standard
  P8 = 'application/pkcs8',// .p8 - PKCS #8 - Private-Key Information Syntax Standard
  AC = 'application/pkix-attr-cert',// .ac - Attribute Certificate
  CER = 'application/pkix-cert',// .cer - Internet Public Key Infrastructure - Certificate
  CRL = 'application/pkix-crl',// .crl - Internet Public Key Infrastructure - Certificate Revocation Lists
  PKIPATH = 'application/pkix-pkipath',// .pkipath - Internet Public Key Infrastructure - Certification Path
  PKI = 'application/pkixcmp',// .pki - Internet Public Key Infrastructure - Certificate Management Protocole
  PLS = 'application/pls+xml',// .pls - Pronunciation Lexicon Specification
  AI = 'application/postscript',// .ai - PostScript
  CWW = 'application/prs.cww',// .cww - CU-Writer
  PSKCXML = 'application/pskc+xml',// .pskcxml - Portable Symmetric Key Container
  RDF = 'application/rdf+xml',// .rdf - Resource Description Framework
  RIF = 'application/reginfo+xml',// .rif - IMS Networks
  RNC = 'application/relax-ng-compact-syntax',// .rnc - Relax NG Compact Syntax
  RLD = 'application/resource-lists-diff+xml',// .rld - XML Resource Lists Diff
  RL = 'application/resource-lists+xml',// .rl - XML Resource Lists
  RS = 'application/rls-services+xml',// .rs - XML Resource Lists
  RSD = 'application/rsd+xml',// .rsd - Really Simple Discovery
  RSS_XML = 'application/rss+xml',// .rss, .xml - RSS - Really Simple Syndication
  RTF = 'application/rtf',// .rtf - Rich Text Format
  SBML = 'application/sbml+xml',// .sbml - Systems Biology Markup Language
  SCQ = 'application/scvp-cv-request',// .scq - Server-Based Certificate Validation Protocol - Validation Request
  SCS = 'application/scvp-cv-response',// .scs - Server-Based Certificate Validation Protocol - Validation Response
  SPQ = 'application/scvp-vp-request',// .spq - Server-Based Certificate Validation Protocol - Validation Policies - Request
  SPP = 'application/scvp-vp-response',// .spp - Server-Based Certificate Validation Protocol - Validation Policies - Response
  SDP = 'application/sdp',// .sdp - Session Description Protocol
  SETPAY = 'application/set-payment-initiation',// .setpay - Secure Electronic Transaction - Payment
  SETREG = 'application/set-registration-initiation',// .setreg - Secure Electronic Transaction - Registration
  SHF = 'application/shf+xml',// .shf - S Hexdump Format
  SMI = 'application/smil+xml',// .smi - Synchronized Multimedia Integration Language
  RQ = 'application/sparql-query',// .rq - SPARQL - Query
  SRX = 'application/sparql-results+xml',// .srx - SPARQL - Results
  GRAM = 'application/srgs',// .gram - Speech Recognition Grammar Specification
  GRXML = 'application/srgs+xml',// .grxml - Speech Recognition Grammar Specification - XML
  SRU = 'application/sru+xml',// .sru - Search/Retrieve via URL Response Format
  SSML = 'application/ssml+xml',// .ssml - Speech Synthesis Markup Language
  TEI = 'application/tei+xml',// .tei - Text Encoding and Interchange
  TFI = 'application/thraud+xml',// .tfi - Sharing Transaction Fraud Data
  TSD = 'application/timestamped-data',// .tsd - Time Stamped Data Envelope
  PLB = 'application/vnd.3gpp.pic-bw-large',// .plb - 3rd Generation Partnership Project - Pic Large
  PSB = 'application/vnd.3gpp.pic-bw-small',// .psb - 3rd Generation Partnership Project - Pic Small
  PVB = 'application/vnd.3gpp.pic-bw-var',// .pvb - 3rd Generation Partnership Project - Pic Var
  TCAP = 'application/vnd.3gpp2.tcap',// .tcap - 3rd Generation Partnership Project - Transaction Capabilities Application Part
  PWN = 'application/vnd.3m.post-it-notes',// .pwn - 3M Post It Notes
  ASO = 'application/vnd.accpac.simply.aso',// .aso - Simply Accounting
  IMP = 'application/vnd.accpac.simply.imp',// .imp - Simply Accounting - Data Import
  ACU = 'application/vnd.acucobol',// .acu - ACU Cobol
  ATC = 'application/vnd.acucorp',// .atc - ACU Cobol
  AIR = 'application/vnd.adobe.air-application-installer-package+zip',// .air - Adobe AIR Application
  FXP = 'application/vnd.adobe.fxp',// .fxp - Adobe Flex Project
  XDP = 'application/vnd.adobe.xdp+xml',// .xdp - Adobe XML Data Package
  XFDF = 'application/vnd.adobe.xfdf',// .xfdf - Adobe XML Forms Data Format
  AHEAD = 'application/vnd.ahead.space',// .ahead - Ahead AIR Application
  AZF = 'application/vnd.airzip.filesecure.azf',// .azf - AirZip FileSECURE
  AZS = 'application/vnd.airzip.filesecure.azs',// .azs - AirZip FileSECURE
  AZW = 'application/vnd.amazon.ebook',// .azw - Amazon Kindle eBook format
  ACC = 'application/vnd.americandynamics.acc',// .acc - Active Content Compression
  AMI = 'application/vnd.amiga.ami',// .ami - AmigaDE
  APK = 'application/vnd.android.package-archive',// .apk - Android Package Archive
  CII = 'application/vnd.anser-web-certificate-issue-initiation',// .cii - ANSER-WEB Terminal Client - Certificate Issue
  FTI = 'application/vnd.anser-web-funds-transfer-initiation',// .fti - ANSER-WEB Terminal Client - Web Funds Transfer
  ATX = 'application/vnd.antix.game-component',// .atx - Antix Game Player
  MPKG = 'application/vnd.apple.installer+xml',// .mpkg - Apple Installer Package
  M3U8 = 'application/vnd.apple.mpegurl',// .m3u8 - Multimedia Playlist Unicode
  SWI = 'application/vnd.aristanetworks.swi',// .swi - Arista Networks Software Image
  AEP = 'application/vnd.audiograph',// .aep - Audiograph
  MPM = 'application/vnd.blueice.multipass',// .mpm - Blueice Research Multipass
  BMI = 'application/vnd.bmi',// .bmi - BMI Drawing Data Interchange
  REP = 'application/vnd.businessobjects',// .rep - BusinessObjects
  CDXML = 'application/vnd.chemdraw+xml',// .cdxml - CambridgeSoft Chem Draw
  MMD = 'application/vnd.chipnuts.karaoke-mmd',// .mmd - Karaoke on Chipnuts Chipsets
  CDY = 'application/vnd.cinderella',// .cdy - Interactive Geometry Software Cinderella
  CLA = 'application/vnd.claymore',// .cla - Claymore Data Files
  RP9 = 'application/vnd.cloanto.rp9',// .rp9 - RetroPlatform Player
  C4G = 'application/vnd.clonk.c4group',// .c4g - Clonk Game
  C11AMC = 'application/vnd.cluetrust.cartomobile-config',// .c11amc - ClueTrust CartoMobile - Config
  C11AMZ = 'application/vnd.cluetrust.cartomobile-config-pkg',// .c11amz - ClueTrust CartoMobile - Config Package
  CSP = 'application/vnd.commonspace',// .csp - Sixth Floor Media - CommonSpace
  CDBCMSG = 'application/vnd.contact.cmsg',// .cdbcmsg - CIM Database
  CMC = 'application/vnd.cosmocaller',// .cmc - CosmoCaller
  CLKX = 'application/vnd.crick.clicker',// .clkx - CrickSoftware - Clicker
  CLKK = 'application/vnd.crick.clicker.keyboard',// .clkk - CrickSoftware - Clicker - Keyboard
  CLKP = 'application/vnd.crick.clicker.palette',// .clkp - CrickSoftware - Clicker - Palette
  CLKT = 'application/vnd.crick.clicker.template',// .clkt - CrickSoftware - Clicker - Template
  CLKW = 'application/vnd.crick.clicker.wordbank',// .clkw - CrickSoftware - Clicker - Wordbank
  WBS = 'application/vnd.criticaltools.wbs+xml',// .wbs - Critical Tools - PERT Chart EXPERT
  PML = 'application/vnd.ctc-posml',// .pml - PosML
  PPD = 'application/vnd.cups-ppd',// .ppd - Adobe PostScript Printer Description File Format
  CAR = 'application/vnd.curl.car',// .car - CURL Applet
  PCURL = 'application/vnd.curl.pcurl',// .pcurl - CURL Applet
  RDZ = 'application/vnd.data-vision.rdz',// .rdz - RemoteDocs R-Viewer
  FE_LAUNCH = 'application/vnd.denovo.fcselayout-link',// .fe_launch - FCS Express Layout Link
  DNA = 'application/vnd.dna',// .dna - New Moon Liftoff/DNA
  MLP = 'application/vnd.dolby.mlp',// .mlp - Dolby Meridian Lossless Packing
  DPG = 'application/vnd.dpgraph',// .dpg - DPGraph
  DFAC = 'application/vnd.dreamfactory',// .dfac - DreamFactory
  AIT = 'application/vnd.dvb.ait',// .ait - Digital Video Broadcasting
  SVC = 'application/vnd.dvb.service',// .svc - Digital Video Broadcasting
  GEO = 'application/vnd.dynageo',// .geo - DynaGeo
  MAG = 'application/vnd.ecowin.chart',// .mag - EcoWin Chart
  NML = 'application/vnd.enliven',// .nml - Enliven Viewer
  ESF = 'application/vnd.epson.esf',// .esf - QUASS Stream Player
  MSF = 'application/vnd.epson.msf',// .msf - QUASS Stream Player
  QAM = 'application/vnd.epson.quickanime',// .qam - QuickAnime Player
  SLT = 'application/vnd.epson.salt',// .slt - SimpleAnimeLite Player
  SSF = 'application/vnd.epson.ssf',// .ssf - QUASS Stream Player
  ES3 = 'application/vnd.eszigno3+xml',// .es3 - MICROSEC e-Szign¢
  EZ2 = 'application/vnd.ezpix-album',// .ez2 - EZPix Secure Photo Album
  EZ3 = 'application/vnd.ezpix-package',// .ez3 - EZPix Secure Photo Album
  FDF = 'application/vnd.fdf',// .fdf - Forms Data Format
  SEED = 'application/vnd.fdsn.seed',// .seed - Digital Siesmograph Networks - SEED Datafiles
  GPH = 'application/vnd.flographit',// .gph - NpGraphIt
  FTC = 'application/vnd.fluxtime.clip',// .ftc - FluxTime Clip
  FM = 'application/vnd.framemaker',// .fm - FrameMaker Normal Format
  FNC = 'application/vnd.frogans.fnc',// .fnc - Frogans Player
  LTF = 'application/vnd.frogans.ltf',// .ltf - Frogans Player
  FSC = 'application/vnd.fsc.weblaunch',// .fsc - Friendly Software Corporation
  OAS = 'application/vnd.fujitsu.oasys',// .oas - Fujitsu Oasys
  OA2 = 'application/vnd.fujitsu.oasys2',// .oa2 - Fujitsu Oasys
  OA3 = 'application/vnd.fujitsu.oasys3',// .oa3 - Fujitsu Oasys
  FG5 = 'application/vnd.fujitsu.oasysgp',// .fg5 - Fujitsu Oasys
  BH2 = 'application/vnd.fujitsu.oasysprs',// .bh2 - Fujitsu Oasys
  DDD = 'application/vnd.fujixerox.ddd',// .ddd - Fujitsu - Xerox 2D CAD Data
  XDW = 'application/vnd.fujixerox.docuworks',// .xdw - Fujitsu - Xerox DocuWorks
  XBD = 'application/vnd.fujixerox.docuworks.binder',// .xbd - Fujitsu - Xerox DocuWorks Binder
  FZS = 'application/vnd.fuzzysheet',// .fzs - FuzzySheet
  TXD = 'application/vnd.genomatix.tuxedo',// .txd - Genomatix Tuxedo Framework
  GGB = 'application/vnd.geogebra.file',// .ggb - GeoGebra
  GGT = 'application/vnd.geogebra.tool',// .ggt - GeoGebra
  GEX = 'application/vnd.geometry-explorer',// .gex - GeoMetry Explorer
  GXT = 'application/vnd.geonext',// .gxt - GEONExT and JSXGraph
  G2W = 'application/vnd.geoplan',// .g2w - GeoplanW
  G3W = 'application/vnd.geospace',// .g3w - GeospacW
  GMX = 'application/vnd.gmx',// .gmx - GameMaker ActiveX
  KML = 'application/vnd.google-earth.kml+xml',// .kml - Google Earth - KML
  KMZ = 'application/vnd.google-earth.kmz',// .kmz - Google Earth - Zipped KML
  GQF = 'application/vnd.grafeq',// .gqf - GrafEq
  GAC = 'application/vnd.groove-account',// .gac - Groove - Account
  GHF = 'application/vnd.groove-help',// .ghf - Groove - Help
  GIM = 'application/vnd.groove-identity-message',// .gim - Groove - Identity Message
  GRV = 'application/vnd.groove-injector',// .grv - Groove - Injector
  GTM = 'application/vnd.groove-tool-message',// .gtm - Groove - Tool Message
  TPL = 'application/vnd.groove-tool-template',// .tpl - Groove - Tool Template
  VCG = 'application/vnd.groove-vcard',// .vcg - Groove - Vcard
  HAL = 'application/vnd.hal+xml',// .hal - Hypertext Application Language
  ZMM = 'application/vnd.handheld-entertainment+xml',// .zmm - ZVUE Media Manager
  HBCI = 'application/vnd.hbci',// .hbci - Homebanking Computer Interface (HBCI)
  LES = 'application/vnd.hhe.lesson-player',// .les - Archipelago Lesson Player
  HPGL = 'application/vnd.hp-hpgl',// .hpgl - HP-GL/2 and HP RTL
  HPID = 'application/vnd.hp-hpid',// .hpid - Hewlett Packard Instant Delivery
  HPS = 'application/vnd.hp-hps',// .hps - Hewlett-Packard's WebPrintSmart
  JLT = 'application/vnd.hp-jlyt',// .jlt - HP Indigo Digital Press - Job Layout Languate
  PCL = 'application/vnd.hp-pcl',// .pcl - HP Printer Command Language
  PCLXL = 'application/vnd.hp-pclxl',// .pclxl - PCL 6 Enhanced (Formely PCL XL)
  SFD_HDSTX = 'application/vnd.hydrostatix.sof-data',// .sfd-hdstx - Hydrostatix Master Suite
  X3D = 'application/vnd.hzn-3d-crossword',// .x3d - 3D Crossword Plugin
  MPY = 'application/vnd.ibm.minipay',// .mpy - MiniPay
  AFP = 'application/vnd.ibm.modcap',// .afp - MO:DCA-P
  IRM = 'application/vnd.ibm.rights-management',// .irm - IBM DB2 Rights Manager
  SC = 'application/vnd.ibm.secure-container',// .sc - IBM Electronic Media Management System - Secure Container
  ICC = 'application/vnd.iccprofile',// .icc - ICC profile
  IGL = 'application/vnd.igloader',// .igl - igLoader
  IVP = 'application/vnd.immervision-ivp',// .ivp - ImmerVision PURE Players
  IVU = 'application/vnd.immervision-ivu',// .ivu - ImmerVision PURE Players
  IGM = 'application/vnd.insors.igm',// .igm - IOCOM Visimeet
  XPW = 'application/vnd.intercon.formnet',// .xpw - Intercon FormNet
  I2G = 'application/vnd.intergeo',// .i2g - Interactive Geometry Software
  QBO = 'application/vnd.intu.qbo',// .qbo - Open Financial Exchange
  QFX = 'application/vnd.intu.qfx',// .qfx - Quicken
  RCPROFILE = 'application/vnd.ipunplugged.rcprofile',// .rcprofile - IP Unplugged Roaming Client
  IRP = 'application/vnd.irepository.package+xml',// .irp - iRepository / Lucidoc Editor
  XPR = 'application/vnd.is-xpr',// .xpr - Express by Infoseek
  FCS = 'application/vnd.isac.fcs',// .fcs - International Society for Advancement of Cytometry
  JAM = 'application/vnd.jam',// .jam - Lightspeed Audio Lab
  RMS = 'application/vnd.jcp.javame.midlet-rms',// .rms - Mobile Information Device Profile
  JISP = 'application/vnd.jisp',// .jisp - RhymBox
  JODA = 'application/vnd.joost.joda-archive',// .joda - Joda Archive
  KTZ = 'application/vnd.kahootz',// .ktz - Kahootz
  KARBON = 'application/vnd.kde.karbon',// .karbon - KDE KOffice Office Suite - Karbon
  CHRT = 'application/vnd.kde.kchart',// .chrt - KDE KOffice Office Suite - KChart
  KFO = 'application/vnd.kde.kformula',// .kfo - KDE KOffice Office Suite - Kformula
  FLW = 'application/vnd.kde.kivio',// .flw - KDE KOffice Office Suite - Kivio
  KON = 'application/vnd.kde.kontour',// .kon - KDE KOffice Office Suite - Kontour
  KPR = 'application/vnd.kde.kpresenter',// .kpr - KDE KOffice Office Suite - Kpresenter
  KSP = 'application/vnd.kde.kspread',// .ksp - KDE KOffice Office Suite - Kspread
  KWD = 'application/vnd.kde.kword',// .kwd - KDE KOffice Office Suite - Kword
  HTKE = 'application/vnd.kenameaapp',// .htke - Kenamea App
  KIA = 'application/vnd.kidspiration',// .kia - Kidspiration
  KNE = 'application/vnd.kinar',// .kne - Kinar Applications
  SKP = 'application/vnd.koan',// .skp - SSEYO Koan Play File
  SSE = 'application/vnd.kodak-descriptor',// .sse - Kodak Storyshare
  LASXML = 'application/vnd.las.las+xml',// .lasxml - Laser App Enterprise
  LBD = 'application/vnd.llamagraphics.life-balance.desktop',// .lbd - Life Balance - Desktop Edition
  LBE = 'application/vnd.llamagraphics.life-balance.exchange+xml',// .lbe - Life Balance - Exchange Format
  APR = 'application/vnd.lotus-approach',// .apr - Lotus Approach
  PRE = 'application/vnd.lotus-freelance',// .pre - Lotus Freelance
  NSF = 'application/vnd.lotus-notes',// .nsf - Lotus Notes
  ORG = 'application/vnd.lotus-organizer',// .org - Lotus Organizer
  SCM = 'application/vnd.lotus-screencam',// .scm - Lotus Screencam
  LWP = 'application/vnd.lotus-wordpro',// .lwp - Lotus Wordpro
  PORTPKG = 'application/vnd.macports.portpkg',// .portpkg - MacPorts Port System
  MCD = 'application/vnd.mcd',// .mcd - Micro CADAM Helix D&D
  MC1 = 'application/vnd.medcalcdata',// .mc1 - MedCalc
  CDKEY = 'application/vnd.mediastation.cdkey',// .cdkey - MediaRemote
  MWF = 'application/vnd.mfer',// .mwf - Medical Waveform Encoding Format
  MFM = 'application/vnd.mfmp',// .mfm - Melody Format for Mobile Platform
  FLO = 'application/vnd.micrografx.flo',// .flo - Micrografx
  IGX = 'application/vnd.micrografx.igx',// .igx - Micrografx iGrafx Professional
  MIF = 'application/vnd.mif',// .mif - FrameMaker Interchange Format
  DAF = 'application/vnd.mobius.daf',// .daf - Mobius Management Systems - UniversalArchive
  DIS = 'application/vnd.mobius.dis',// .dis - Mobius Management Systems - Distribution Database
  MBK = 'application/vnd.mobius.mbk',// .mbk - Mobius Management Systems - Basket file
  MQY = 'application/vnd.mobius.mqy',// .mqy - Mobius Management Systems - Query File
  MSL = 'application/vnd.mobius.msl',// .msl - Mobius Management Systems - Script Language
  PLC = 'application/vnd.mobius.plc',// .plc - Mobius Management Systems - Policy Definition Language File
  TXF = 'application/vnd.mobius.txf',// .txf - Mobius Management Systems - Topic Index File
  MPN = 'application/vnd.mophun.application',// .mpn - Mophun VM
  MPC = 'application/vnd.mophun.certificate',// .mpc - Mophun Certificate
  XUL = 'application/vnd.mozilla.xul+xml',// .xul - XUL - XML User Interface Language
  CIL = 'application/vnd.ms-artgalry',// .cil - Microsoft Artgalry
  CAB = 'application/vnd.ms-cab-compressed',// .cab - Microsoft Cabinet File
  XLS = 'application/vnd.ms-excel',// .xls - Microsoft Excel
  XLAM = 'application/vnd.ms-excel.addin.macroenabled.12',// .xlam - Microsoft Excel - Add-In File
  XLSB = 'application/vnd.ms-excel.sheet.binary.macroenabled.12',// .xlsb - Microsoft Excel - Binary Workbook
  XLSM = 'application/vnd.ms-excel.sheet.macroenabled.12',// .xlsm - Microsoft Excel - Macro-Enabled Workbook
  XLTM = 'application/vnd.ms-excel.template.macroenabled.12',// .xltm - Microsoft Excel - Macro-Enabled Template File
  EOT = 'application/vnd.ms-fontobject',// .eot - Microsoft Embedded OpenType
  CHM = 'application/vnd.ms-htmlhelp',// .chm - Microsoft Html Help File
  IMS = 'application/vnd.ms-ims',// .ims - Microsoft Class Server
  LRM = 'application/vnd.ms-lrm',// .lrm - Microsoft Learning Resource Module
  THMX = 'application/vnd.ms-officetheme',// .thmx - Microsoft Office System Release Theme
  CAT = 'application/vnd.ms-pki.seccat',// .cat - Microsoft Trust UI Provider - Security Catalog
  STL = 'application/vnd.ms-pki.stl',// .stl - Microsoft Trust UI Provider - Certificate Trust Link
  PPT = 'application/vnd.ms-powerpoint',// .ppt - Microsoft PowerPoint
  PPAM = 'application/vnd.ms-powerpoint.addin.macroenabled.12',// .ppam - Microsoft PowerPoint - Add-in file
  PPTM = 'application/vnd.ms-powerpoint.presentation.macroenabled.12',// .pptm - Microsoft PowerPoint - Macro-Enabled Presentation File
  SLDM = 'application/vnd.ms-powerpoint.slide.macroenabled.12',// .sldm - Microsoft PowerPoint - Macro-Enabled Open XML Slide
  PPSM = 'application/vnd.ms-powerpoint.slideshow.macroenabled.12',// .ppsm - Microsoft PowerPoint - Macro-Enabled Slide Show File
  POTM = 'application/vnd.ms-powerpoint.template.macroenabled.12',// .potm - Microsoft PowerPoint - Macro-Enabled Template File
  MPP = 'application/vnd.ms-project',// .mpp - Microsoft Project
  DOCM = 'application/vnd.ms-word.document.macroenabled.12',// .docm - Microsoft Word - Macro-Enabled Document
  DOTM = 'application/vnd.ms-word.template.macroenabled.12',// .dotm - Microsoft Word - Macro-Enabled Template
  WPS = 'application/vnd.ms-works',// .wps - Microsoft Works
  WPL = 'application/vnd.ms-wpl',// .wpl - Microsoft Windows Media Player Playlist
  XPS = 'application/vnd.ms-xpsdocument',// .xps - Microsoft XML Paper Specification
  MSEQ = 'application/vnd.mseq',// .mseq - 3GPP MSEQ File
  MUS = 'application/vnd.musician',// .mus - MUsical Score Interpreted Code Invented for the ASCII designation of Notation
  MSTY = 'application/vnd.muvee.style',// .msty - Muvee Automatic Video Editing
  NLU = 'application/vnd.neurolanguage.nlu',// .nlu - neuroLanguage
  NND = 'application/vnd.noblenet-directory',// .nnd - NobleNet Directory
  NNS = 'application/vnd.noblenet-sealer',// .nns - NobleNet Sealer
  NNW = 'application/vnd.noblenet-web',// .nnw - NobleNet Web
  NGDAT = 'application/vnd.nokia.n-gage.data',// .ngdat - N-Gage Game Data
  N_GAGE = 'application/vnd.nokia.n-gage.symbian.install',// .n-gage - N-Gage Game Installer
  RPST = 'application/vnd.nokia.radio-preset',// .rpst - Nokia Radio Application - Preset
  RPSS = 'application/vnd.nokia.radio-presets',// .rpss - Nokia Radio Application - Preset
  EDM = 'application/vnd.novadigm.edm',// .edm - Novadigm's RADIA and EDM products
  EDX = 'application/vnd.novadigm.edx',// .edx - Novadigm's RADIA and EDM products
  EXT = 'application/vnd.novadigm.ext',// .ext - Novadigm's RADIA and EDM products
  ODC = 'application/vnd.oasis.opendocument.chart',// .odc - OpenDocument Chart
  OTC = 'application/vnd.oasis.opendocument.chart-template',// .otc - OpenDocument Chart Template
  ODB = 'application/vnd.oasis.opendocument.database',// .odb - OpenDocument Database
  ODF = 'application/vnd.oasis.opendocument.formula',// .odf - OpenDocument Formula
  ODFT = 'application/vnd.oasis.opendocument.formula-template',// .odft - OpenDocument Formula Template
  ODG = 'application/vnd.oasis.opendocument.graphics',// .odg - OpenDocument Graphics
  OTG = 'application/vnd.oasis.opendocument.graphics-template',// .otg - OpenDocument Graphics Template
  ODI = 'application/vnd.oasis.opendocument.image',// .odi - OpenDocument Image
  OTI = 'application/vnd.oasis.opendocument.image-template',// .oti - OpenDocument Image Template
  ODP = 'application/vnd.oasis.opendocument.presentation',// .odp - OpenDocument Presentation
  OTP = 'application/vnd.oasis.opendocument.presentation-template',// .otp - OpenDocument Presentation Template
  ODS = 'application/vnd.oasis.opendocument.spreadsheet',// .ods - OpenDocument Spreadsheet
  OTS = 'application/vnd.oasis.opendocument.spreadsheet-template',// .ots - OpenDocument Spreadsheet Template
  ODT = 'application/vnd.oasis.opendocument.text',// .odt - OpenDocument Text
  ODM = 'application/vnd.oasis.opendocument.text-master',// .odm - OpenDocument Text Master
  OTT = 'application/vnd.oasis.opendocument.text-template',// .ott - OpenDocument Text Template
  OTH = 'application/vnd.oasis.opendocument.text-web',// .oth - Open Document Text Web
  XO = 'application/vnd.olpc-sugar',// .xo - Sugar Linux Application Bundle
  DD2 = 'application/vnd.oma.dd2+xml',// .dd2 - OMA Download Agents
  OXT = 'application/vnd.openofficeorg.extension',// .oxt - Open Office Extension
  PPTX = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',// .pptx - Microsoft Office - OOXML - Presentation
  SLDX = 'application/vnd.openxmlformats-officedocument.presentationml.slide',// .sldx - Microsoft Office - OOXML - Presentation (Slide)
  PPSX = 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',// .ppsx - Microsoft Office - OOXML - Presentation (Slideshow)
  POTX = 'application/vnd.openxmlformats-officedocument.presentationml.template',// .potx - Microsoft Office - OOXML - Presentation Template
  XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',// .xlsx - Microsoft Office - OOXML - Spreadsheet
  XLTX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',// .xltx - Microsoft Office - OOXML - Spreadsheet Template
  DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',// .docx - Microsoft Office - OOXML - Word Document
  DOTX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',// .dotx - Microsoft Office - OOXML - Word Document Template
  MGP = 'application/vnd.osgeo.mapguide.package',// .mgp - MapGuide DBXML
  DP = 'application/vnd.osgi.dp',// .dp - OSGi Deployment Package
  PDB = 'application/vnd.palm',// .pdb - PalmOS Data
  PAW = 'application/vnd.pawaafile',// .paw - PawaaFILE
  STR = 'application/vnd.pg.format',// .str - Proprietary P&G Standard Reporting System
  EI6 = 'application/vnd.pg.osasli',// .ei6 - Proprietary P&G Standard Reporting System
  EFIF = 'application/vnd.picsel',// .efif - Pcsel eFIF File
  WG = 'application/vnd.pmi.widget',// .wg - Qualcomm's Plaza Mobile Internet
  PLF = 'application/vnd.pocketlearn',// .plf - PocketLearn Viewers
  PBD = 'application/vnd.powerbuilder6',// .pbd - PowerBuilder
  BOX = 'application/vnd.previewsystems.box',// .box - Preview Systems ZipLock/VBox
  MGZ = 'application/vnd.proteus.magazine',// .mgz - EFI Proteus
  QPS = 'application/vnd.publishare-delta-tree',// .qps - PubliShare Objects
  PTID = 'application/vnd.pvi.ptid1',// .ptid - Princeton Video Image
  QXD = 'application/vnd.quark.quarkxpress',// .qxd - QuarkXpress
  BED = 'application/vnd.realvnc.bed',// .bed - RealVNC
  MXL = 'application/vnd.recordare.musicxml',// .mxl - Recordare Applications
  MUSICXML = 'application/vnd.recordare.musicxml+xml',// .musicxml - Recordare Applications
  CRYPTONOTE = 'application/vnd.rig.cryptonote',// .cryptonote - CryptoNote
  COD = 'application/vnd.rim.cod',// .cod - Blackberry COD File
  RM = 'application/vnd.rn-realmedia',// .rm - RealMedia
  LINK66 = 'application/vnd.route66.link66+xml',// .link66 - ROUTE 66 Location Based Services
  ST = 'application/vnd.sailingtracker.track',// .st - SailingTracker
  SEE = 'application/vnd.seemail',// .see - SeeMail
  SEMA = 'application/vnd.sema',// .sema - Secured eMail
  SEMD = 'application/vnd.semd',// .semd - Secured eMail
  SEMF = 'application/vnd.semf',// .semf - Secured eMail
  IFM = 'application/vnd.shana.informed.formdata',// .ifm - Shana Informed Filler
  ITP = 'application/vnd.shana.informed.formtemplate',// .itp - Shana Informed Filler
  IIF = 'application/vnd.shana.informed.interchange',// .iif - Shana Informed Filler
  IPK = 'application/vnd.shana.informed.package',// .ipk - Shana Informed Filler
  TWD = 'application/vnd.simtech-mindmapper',// .twd - SimTech MindMapper
  MMF = 'application/vnd.smaf',// .mmf - SMAF File
  TEACHER = 'application/vnd.smart.teacher',// .teacher - SMART Technologies Apps
  SDKM = 'application/vnd.solent.sdkm+xml',// .sdkm - SudokuMagic
  DXP = 'application/vnd.spotfire.dxp',// .dxp - TIBCO Spotfire
  SFS = 'application/vnd.spotfire.sfs',// .sfs - TIBCO Spotfire
  SDC = 'application/vnd.stardivision.calc',// .sdc - StarOffice - Calc
  SDA = 'application/vnd.stardivision.draw',// .sda - StarOffice - Draw
  SDD = 'application/vnd.stardivision.impress',// .sdd - StarOffice - Impress
  SMF = 'application/vnd.stardivision.math',// .smf - StarOffice - Math
  SDW = 'application/vnd.stardivision.writer',// .sdw - StarOffice - Writer
  SGL = 'application/vnd.stardivision.writer-global',// .sgl - StarOffice - Writer (Global)
  SM = 'application/vnd.stepmania.stepchart',// .sm - StepMania
  SXC = 'application/vnd.sun.xml.calc',// .sxc - OpenOffice - Calc (Spreadsheet)
  STC = 'application/vnd.sun.xml.calc.template',// .stc - OpenOffice - Calc Template (Spreadsheet)
  SXD = 'application/vnd.sun.xml.draw',// .sxd - OpenOffice - Draw (Graphics)
  STD = 'application/vnd.sun.xml.draw.template',// .std - OpenOffice - Draw Template (Graphics)
  SXI = 'application/vnd.sun.xml.impress',// .sxi - OpenOffice - Impress (Presentation)
  STI = 'application/vnd.sun.xml.impress.template',// .sti - OpenOffice - Impress Template (Presentation)
  SXM = 'application/vnd.sun.xml.math',// .sxm - OpenOffice - Math (Formula)
  SXW = 'application/vnd.sun.xml.writer',// .sxw - OpenOffice - Writer (Text - HTML)
  SXG = 'application/vnd.sun.xml.writer.global',// .sxg - OpenOffice - Writer (Text - HTML)
  STW = 'application/vnd.sun.xml.writer.template',// .stw - OpenOffice - Writer Template (Text - HTML)
  SUS = 'application/vnd.sus-calendar',// .sus - ScheduleUs
  SVD = 'application/vnd.svd',// .svd - SourceView Document
  SIS = 'application/vnd.symbian.install',// .sis - Symbian Install Package
  BDM = 'application/vnd.syncml.dm+wbxml',// .bdm - SyncML - Device Management
  XDM = 'application/vnd.syncml.dm+xml',// .xdm - SyncML - Device Management
  XSM = 'application/vnd.syncml+xml',// .xsm - SyncML
  TAO = 'application/vnd.tao.intent-module-archive',// .tao - Tao Intent
  TMO = 'application/vnd.tmobile-livetv',// .tmo - MobileTV
  TPT = 'application/vnd.trid.tpt',// .tpt - TRI Systems Config
  MXS = 'application/vnd.triscape.mxs',// .mxs - Triscape Map Explorer
  TRA = 'application/vnd.trueapp',// .tra - True BASIC
  UFD = 'application/vnd.ufdl',// .ufd - Universal Forms Description Language
  UTZ = 'application/vnd.uiq.theme',// .utz - User Interface Quartz - Theme (Symbian)
  UMJ = 'application/vnd.umajin',// .umj - UMAJIN
  UNITYWEB = 'application/vnd.unity',// .unityweb - Unity 3d
  UOML = 'application/vnd.uoml+xml',// .uoml - Unique Object Markup Language
  VCX = 'application/vnd.vcx',// .vcx - VirtualCatalog
  VSD = 'application/vnd.visio',// .vsd - Microsoft Visio
  VSDX = 'application/vnd.visio2013',// .vsdx - Microsoft Visio 2013
  VIS = 'application/vnd.visionary',// .vis - Visionary
  VSF = 'application/vnd.vsf',// .vsf - Viewport+
  WBXML = 'application/vnd.wap.wbxml',// .wbxml - WAP Binary XML (WBXML)
  WMLC = 'application/vnd.wap.wmlc',// .wmlc - Compiled Wireless Markup Language (WMLC)
  WMLSC = 'application/vnd.wap.wmlscriptc',// .wmlsc - WMLScript
  WTB = 'application/vnd.webturbo',// .wtb - WebTurbo
  NBP = 'application/vnd.wolfram.player',// .nbp - Mathematica Notebook Player
  WPD = 'application/vnd.wordperfect',// .wpd - Wordperfect
  WQD = 'application/vnd.wqd',// .wqd - SundaHus WQ
  STF = 'application/vnd.wt.stf',// .stf - Worldtalk
  XAR = 'application/vnd.xara',// .xar - CorelXARA
  XFDL = 'application/vnd.xfdl',// .xfdl - Extensible Forms Description Language
  HVD = 'application/vnd.yamaha.hv-dic',// .hvd - HV Voice Dictionary
  HVS = 'application/vnd.yamaha.hv-script',// .hvs - HV Script
  HVP = 'application/vnd.yamaha.hv-voice',// .hvp - HV Voice Parameter
  OSF = 'application/vnd.yamaha.openscoreformat',// .osf - Open Score Format
  OSFPVG = 'application/vnd.yamaha.openscoreformat.osfpvg+xml',// .osfpvg - OSFPVG
  SAF = 'application/vnd.yamaha.smaf-audio',// .saf - SMAF Audio
  SPF = 'application/vnd.yamaha.smaf-phrase',// .spf - SMAF Phrase
  CMP = 'application/vnd.yellowriver-custom-menu',// .cmp - CustomMenu
  ZIR = 'application/vnd.zul',// .zir - Z.U.L. Geometry
  ZAZ = 'application/vnd.zzazz.deck+xml',// .zaz - Zzazz Deck
  VXML = 'application/voicexml+xml',// .vxml - VoiceXML
  WGT = 'application/widget',// .wgt - Widget Packaging and XML Configuration
  HLP = 'application/winhlp',// .hlp - WinHelp
  WSDL = 'application/wsdl+xml',// .wsdl - WSDL - Web Services Description Language
  WSPOLICY = 'application/wspolicy+xml',// .wspolicy - Web Services Policy
  ZZ = 'application/x-7z-compressed',// .7z - 7-Zip
  ABW = 'application/x-abiword',// .abw - AbiWord
  ACE = 'application/x-ace-compressed',// .ace - Ace Archive
  DMG = 'application/x-apple-diskimage',// .dmg - Apple Disk Image
  AAB = 'application/x-authorware-bin',// .aab - Adobe (Macropedia) Authorware - Binary File
  AAM = 'application/x-authorware-map',// .aam - Adobe (Macropedia) Authorware - Map
  AAS = 'application/x-authorware-seg',// .aas - Adobe (Macropedia) Authorware - Segment File
  BCPIO = 'application/x-bcpio',// .bcpio - Binary CPIO Archive
  TORRENT = 'application/x-bittorrent',// .torrent - BitTorrent
  BZ = 'application/x-bzip',// .bz - Bzip Archive
  BZ2 = 'application/x-bzip2',// .bz2 - Bzip2 Archive
  VCD = 'application/x-cdlink',// .vcd - Video CD
  CHAT = 'application/x-chat',// .chat - pIRCh
  PGN = 'application/x-chess-pgn',// .pgn - Portable Game Notation (Chess Games)
  CPIO = 'application/x-cpio',// .cpio - CPIO Archive
  CSH = 'application/x-csh',// .csh - C Shell Script
  DEB = 'application/x-debian-package',// .deb - Debian Package
  DIR = 'application/x-director',// .dir - Adobe Shockwave Player
  WAD = 'application/x-doom',// .wad - Doom Video Game
  NCX = 'application/x-dtbncx+xml',// .ncx - Navigation Control file for XML (for ePub)
  DTB = 'application/x-dtbook+xml',// .dtb - Digital Talking Book
  RES = 'application/x-dtbresource+xml',// .res - Digital Talking Book - Resource File
  DVI = 'application/x-dvi',// .dvi - Device Independent File Format (DVI)
  BDF = 'application/x-font-bdf',// .bdf - Glyph Bitmap Distribution Format
  GSF = 'application/x-font-ghostscript',// .gsf - Ghostscript Font
  PSF = 'application/x-font-linux-psf',// .psf - PSF Fonts
  OTF = 'application/x-font-otf',// .otf - OpenType Font File
  PCF = 'application/x-font-pcf',// .pcf - Portable Compiled Format
  SNF = 'application/x-font-snf',// .snf - Server Normal Format
  TTF = 'application/x-font-ttf',// .ttf - TrueType Font
  PFA = 'application/x-font-type1',// .pfa - PostScript Fonts
  WOFF = 'application/x-font-woff',// .woff - Web Open Font Format
  SPL = 'application/x-futuresplash',// .spl - FutureSplash Animator
  GNUMERIC = 'application/x-gnumeric',// .gnumeric - Gnumeric
  GTAR = 'application/x-gtar',// .gtar - GNU Tar Files
  HDF = 'application/x-hdf',// .hdf - Hierarchical Data Format
  JNLP = 'application/x-java-jnlp-file',// .jnlp - Java Network Launching Protocol
  LATEX = 'application/x-latex',// .latex - LaTeX
  PRC = 'application/x-mobipocket-ebook',// .prc - Mobipocket
  APPLICATION = 'application/x-ms-application',// .application - Microsoft ClickOnce
  WMD = 'application/x-ms-wmd',// .wmd - Microsoft Windows Media Player Download Package
  WMZ = 'application/x-ms-wmz',// .wmz - Microsoft Windows Media Player Skin Package
  XBAP = 'application/x-ms-xbap',// .xbap - Microsoft XAML Browser Application
  MDB = 'application/x-msaccess',// .mdb - Microsoft Access
  OBD = 'application/x-msbinder',// .obd - Microsoft Office Binder
  CRD = 'application/x-mscardfile',// .crd - Microsoft Information Card
  CLP = 'application/x-msclip',// .clp - Microsoft Clipboard Clip
  EXE = 'application/x-msdownload',// .exe - Microsoft Application
  MVB = 'application/x-msmediaview',// .mvb - Microsoft MediaView
  WMF = 'application/x-msmetafile',// .wmf - Microsoft Windows Metafile
  MNY = 'application/x-msmoney',// .mny - Microsoft Money
  PUB = 'application/x-mspublisher',// .pub - Microsoft Publisher
  SCD = 'application/x-msschedule',// .scd - Microsoft Schedule+
  TRM = 'application/x-msterminal',// .trm - Microsoft Windows Terminal Services
  WRI = 'application/x-mswrite',// .wri - Microsoft Wordpad
  NC = 'application/x-netcdf',// .nc - Network Common Data Form (NetCDF)
  P12 = 'application/x-pkcs12',// .p12 - PKCS #12 - Personal Information Exchange Syntax Standard
  P7B = 'application/x-pkcs7-certificates',// .p7b - PKCS #7 - Cryptographic Message Syntax Standard (Certificates)
  P7R = 'application/x-pkcs7-certreqresp',// .p7r - PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)
  RAR = 'application/x-rar-compressed',// .rar - RAR Archive
  SH = 'application/x-sh',// .sh - Bourne Shell Script
  SHAR = 'application/x-shar',// .shar - Shell Archive
  SWF = 'application/x-shockwave-flash',// .swf - Adobe Flash
  XAP = 'application/x-silverlight-app',// .xap - Microsoft Silverlight
  SIT = 'application/x-stuffit',// .sit - Stuffit Archive
  SITX = 'application/x-stuffitx',// .sitx - Stuffit Archive
  SV4CPIO = 'application/x-sv4cpio',// .sv4cpio - System V Release 4 CPIO Archive
  SV4CRC = 'application/x-sv4crc',// .sv4crc - System V Release 4 CPIO Checksum Data
  TAR = 'application/x-tar',// .tar - Tar File (Tape Archive)
  TCL = 'application/x-tcl',// .tcl - Tcl Script
  TEX = 'application/x-tex',// .tex - TeX
  TFM = 'application/x-tex-tfm',// .tfm - TeX Font Metric
  TEXINFO = 'application/x-texinfo',// .texinfo - GNU Texinfo Document
  USTAR = 'application/x-ustar',// .ustar - Ustar (Uniform Standard Tape Archive)
  SRC = 'application/x-wais-source',// .src - WAIS Source
  DER = 'application/x-x509-ca-cert',// .der - X.509 Certificate
  FIG = 'application/x-xfig',// .fig - Xfig
  XPI = 'application/x-xpinstall',// .xpi - XPInstall - Mozilla
  XDF = 'application/xcap-diff+xml',// .xdf - XML Configuration Access Protocol - XCAP Diff
  XENC = 'application/xenc+xml',// .xenc - XML Encryption Syntax and Processing
  XHTML = 'application/xhtml+xml',// .xhtml - XHTML - The Extensible HyperText Markup Language
  XML = 'application/xml',// .xml - XML - Extensible Markup Language
  DTD = 'application/xml-dtd',// .dtd - Document Type Definition
  XOP = 'application/xop+xml',// .xop - XML-Binary Optimized Packaging
  XSLT = 'application/xslt+xml',// .xslt - XML Transformations
  XSPF = 'application/xspf+xml',// .xspf - XSPF - XML Shareable Playlist Format
  MXML = 'application/xv+xml',// .mxml - MXML
  YANG = 'application/yang',// .yang - YANG Data Modeling Language
  YIN = 'application/yin+xml',// .yin - YIN (YANG - XML)
  ZIP = 'application/zip',// .zip - Zip Archive
}
